name: "ksec"
version: "0.1.0"
usage: "Manage Kubernetes Secrets through Helm"
description: "Helm plugin that simplifies the management of Kubernetes Secrets"
ignoreFlags: false
useTunnel: false
command: "$HELM_PLUGIN_DIR/ksec"
