name: "ksec"
usage: "Manage Kubernetes Secrets through Helm"
description: "Helm plugin that simplifies the management of Kubernetes Secrets"
ignoreFlags: false
useTunnel: false
command: "$HELM_PLUGIN_DIR/ksec"
hooks:
  install: "$HELM_PLUGIN_DIR/scripts/install-binary.sh"
